### ISSUE TITLE
Remove adamsregrid from EnsoUvcdatToolsLib.py

### ISSUE THREAD

**Issue by lee1043** [eguil/ENSO_metrics#19]
@yyplanton As a part of practicing more intense use of this issue board for code development, I suggest remove `adamsregrid` from code [here](https://github.com/eguil/ENSO_metrics/blob/master/lib/EnsoUvcdatToolsLib.py) because it is not included or supported by CDAT anymore. 

@doutriaux1 @gleckler1 please correct me if I am wrong.

**Comment by lee1043** [comment]
`adamsregrid` is part of `regridpack` which used to be part of uvcdat-2.12, checked with @doutriaux1 by looking at:
https://github.com/CDAT/cdat/blob/master/contrib/regridpack/regridmodule.doc
```anaconda search -t conda regridpack```

**Comment by eguil** [comment]
Done !

**Comment by lee1043** [comment]
https://github.com/eguil/ENSO_metrics/pull/23 resolves this issue
