### ISSUE TITLE
Make educational example of different normalisation, color bar, etc...

### ISSUE THREAD

**Issue by eguil** [eguil/ENSO_metrics#34]
Use a MC to show different options of portrait plots:
 - relative diff, RMSE, ratio
 - shading vs. numbers
 - etc...

**Comment by lee1043** [comment]
# RMSE Portrait plot
## Color for normalized metrics value
![ENSO_perf_cmip_5and6_Rmse_PP_SidebySide_annotated](https://user-images.githubusercontent.com/17091564/57502418-90221f80-72a0-11e9-94de-1cfd8741d073.png)
## Color for NON-normalized metrics value
![ENSO_perf_cmip_5and6_Rmse_PP_SidebySideColor-Not-Normalized_annotated](https://user-images.githubusercontent.com/17091564/57502428-92847980-72a0-11e9-91ed-99c66fb0faf9.png)
# Non-RMSE Portrait plot
## Color for normalized metrics value
![ENSO_perf_cmip_5and6_nonRmse_PP_SidebySide_annotated](https://user-images.githubusercontent.com/17091564/57502435-96180080-72a0-11e9-9e0c-d01fa21e1ce3.png)
## Color for NON-normalized metrics value
![ENSO_perf_cmip_5and6_nonRmse_PP_SidebySideColor-Not-Normalized_annotated](https://user-images.githubusercontent.com/17091564/57502436-97e1c400-72a0-11e9-8099-57104c594d0c.png)

**Comment by lee1043** [comment]
@eguil @yyplanton @gleckler1 what do you think? Any feedback/suggestion welcome

**Comment by gleckler1** [comment]
@eguil @yyplanton @gleckler1  Great examples Jiwoo.  For the non-normalized RMSE you could make an effort to encapsulate more rows by change the color min/max to 0-5... with that more of the rows will probably not be blue but it will still clearly demonstrate the issue of comparing results from different metrics.

**Comment by lee1043** [comment]
@gleckler1 great idea, which look like below. 

## non-normalized RMSE (example 2)
![ENSO_perf_cmip_5and6_Rmse_PP_SidebySideColor-Not-Normalized_annotated](https://user-images.githubusercontent.com/17091564/57563314-50ffd700-7351-11e9-86bb-8430aacfe878.png)

**Comment by eguil** [comment]
- Use these in presentation for CLIVAR group
- try using max of metrics or average of 5 max
- try defining expert-chosen thresholds

**Comment by lee1043** [comment]
![ENSO_perf_cmip_5and6_Rmse_PP_SidebySide_SidebySide_NormalizedByMaximum_annotated](https://user-images.githubusercontent.com/17091564/57647494-f3999f00-7577-11e9-9470-87c07ac45139.png)
![ENSO_perf_cmip_5and6_nonRmse_PP_SidebySide_SidebySide_NormalizedByMaximum_annotated](https://user-images.githubusercontent.com/17091564/57647499-f5fbf900-7577-11e9-9683-a8b68b826945.png)

Another example: Normalized by maximum of each row.

**Comment by eguil** [comment]
why don't we get any reds ?

**Comment by lee1043** [comment]
It is normalized as: `[E(model) - E(max)] / E(max)`, which makes all numbers as negative. Please let me know if you were indicating in different way. I am not sure you meat `[E(model) - E(median)] / E(max)`?

**Comment by gleckler1** [comment]
I think they meant E(model)/E(max) … no E(median).   So some should be close to one.

**Comment by lee1043** [comment]
![ENSO_perf_cmip_5and6_Rmse_PP_SidebySide_SidebySide_NormalizedByMaximum_annotated](https://user-images.githubusercontent.com/17091564/57650765-627af600-7580-11e9-8ba2-2165fdf27435.png)
![ENSO_perf_cmip_5and6_nonRmse_PP_SidebySide_SidebySide_NormalizedByMaximum_annotated](https://user-images.githubusercontent.com/17091564/57650770-6444b980-7580-11e9-8f14-0e81e2548fb1.png)

Another example 2: Normalized by maximum of each row.
`E(model) / E(max)`
